export enum EAcceptInvitationResponse {
  'OK_ACCEPTED' = 'OK_ACCEPTED',
  'FAIL_SHOULD_PROVIDE_NEW_PASSWORD' = 'FAIL_SHOULD_PROVIDE_NEW_PASSWORD',
  'FAIL_PASSWORD_ALREADY_SET' = 'FAIL_PASSWORD_ALREADY_SET',
  'FAIL_NOT_EXISTS_OR_EXPIRED_OR_ACCEPTED' = 'FAIL_NOT_EXISTS_OR_EXPIRED_OR_ACCEPTED'
}
