export enum EResetPasswordConfirm {
  'OK_NEW_PASSWORD_SET' = 'OK_NEW_PASSWORD_SET',
  'OK_LINK_IS_VALID_PROVIDE_PASSWORD' = 'OK_LINK_IS_VALID_PROVIDE_PASSWORD',
  'FAIL_NEW_PASSWORD_INSECURE' = 'FAIL_NEW_PASSWORD_INSECURE',
  'FAIL_RESET_LINK_EXPIRED' = 'FAIL_RESET_LINK_EXPIRED'
}
